### ISSUE TITLE
Witryna

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#10]
Inf. o projekcie, nie można wpisać wartości po przecinku, wyskakuje komunikat , że wart. dziesiętna jest niepoprawna

**Comment by oramm** [comment]
Błąd poprawiony, ale trzeba zamiast przecinka używać kropki (notacja US).
W przyszłości dorobię system tak, żeby rozumiał notację EU liczb. 
Do tego czasu zgłoszenie zostawiam jako otwarte.

**Comment by oramm** [comment]
@Tymczyszyn Jednak zamykam zgłoszenie i otwieram nowe, bo tytuł Witryna za cholerę nie odpowiada treści.
