### ISSUE TITLE
sprawy związane z umową Wykonawcy robót - braki

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#100]
Brakuje nam w witrynie kamienia/spraw dot. umowy z Wykonawcą robót (danego kontraktu), żeby móc dodawać zadania z tym związane, np. dot. zmiana personelu Wykonawcy.
Na GD tworzy się folder "umowa" ale nie ma jw. możliwości dodania zadań z tym związanych, tj. w powiązaniu z danym kontraktem (umową Wykonawcy), chyba, że to ma być w "Roboty-nadzór" /Rozpoczęcie robót lub Administracja/Sprawy ogólne/koordynacja pod umową IK, ale wtedy to zadanie nie będzie w scrumie powiązane z danym kontraktem.
Jest kamień Administracja- umowa zewn. ale nie wiem co tu masz na myśli, ja tu dla KOB wrzuciłam wszystkie dokumenty SKARSA jakie stworzyli nadzorując kontrakt jako IK tymczasowy.

**Comment by oramm** [comment]
Właśnie kamień typu 'Administracja- umowa zewn' służy do spraw zwiąanzych z administraą Kontraktem na roboty do którego należy ten kamień.

To jest analogiczny kamień jak 'Administracja', który dotyczy umów ENVI.

**Comment by oramm** [comment]
> Jest kamień Administracja- umowa zewn. ale nie wiem co tu masz na myśli, ja tu dla KOB wrzuciłam wszystkie dokumenty SKARSA jakie stworzyli nadzorując kontrakt jako IK tymczasowy.

Sprawy naszych podwykonawców powinny być załatwiane w ramach kamoenia Administracja przy naszej umowie.

**Comment by Tymczyszyn** [comment]
dot. kontraktu - teraz mamy folder 00-Umowa z Wykonawcą i równorzędny 00 Administracja - umowa zewnętrzna ...

**Comment by Tymczyszyn** [comment]
"Sprawy naszych podwykonawców powinny być załatwiane w ramach kamoenia Administracja przy naszej umowie." - tak,  ale IK tymczasowy nie był naszym podwykonawcą

**Comment by oramm** [comment]
> dot. kontraktu - teraz mamy folder 00-Umowa z Wykonawcą i równorzędny 00 Administracja - umowa zewnętrzna ...

W fodlerze umowa z wykonawcą są pliki umowy z wykonawca, a folder dla sprawy typu 00 Administracja - umowa zewnętrzna zawiera korespondencję dot. umowy (wezwania, wyjaśnienia...

W sumie miżna by scalić te dwa foldery poprzez pozbycie się foleru Umowa z Wykonawcą...
Do przemyślenia

**Comment by oramm** [comment]
> "Sprawy naszych podwykonawców powinny być załatwiane w ramach kamoenia Administracja przy naszej umowie." - tak, ale IK tymczasowy nie był naszym podwykonawcą

TO faktycznie idzie do jakiegoś ogólenego folderru. Idealnie byłoby założyć oddzielny kontrakt na umowę dla IK tymczasowego. Jako kontrakt typu 'Usługi' - nie envi
