### ISSUE TITLE
Edytuj dane pisma

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#102]
Przy "Edytuj dane pisma" i wierszach z komentarzem "Jeżeli nie chcesz przypisywać kolejnej sprawy do pisma, możesz to pole zignorować" powinna być widoczna ta wybrana wcześniej sprawa, bo jak pismo będzie dotyczyło wielu spraw, to się póxniej nie pamięta do których jest już powiązane, a  o której zapomnieliśmy np. i chcemy teraz zrobić to powiązanie

**Comment by Tymczyszyn** [comment]
bo jak nie widzę, to robię to bez sensu drugi raz dla pewności

**Comment by oramm** [comment]
Przypisane wcześniej sprawy powinny by widoczne w postaci chipsów szarych pod polem wyboru sprawy. System nie pozwala zapisać zmian jeśli nie ma zapamiętanej pzrynajmniej jednej sprawy

**Comment by oramm** [comment]
o widzę na przykładzie 

> Numer 123, Utworzono: 2019-11-20, Otrzymano: 2019-11-21,
> Opis: test 8
> Nadawca: ATA - TECHNIK
Że jednak przeszło pismo bez spraw przypisanych. sprawdzę to

**Comment by oramm** [comment]
ok sprawdziłem i chyba błąd usunąłem. Jak wrzucę na serwer dam znać, żeby przetestować czy faktycznie blokuje zapisanie gdy nie wybrano żednej sprawy,

**Comment by oramm** [comment]
@Tymczyszyn Zobacz czy już jest ok.
Tak jak pisałem pole wyboru spraw jest tylko do dodwania kolejnych spraw. Wybrane wcześniej sprawy są w postaci szarych chipsów
![obraz](https://user-images.githubusercontent.com/33371875/68989913-271df480-084d-11ea-888c-0dcd4f45f275.png)

**Comment by oramm** [comment]
jeśli działa i wyjaśniłem mechanizm to zamknij wątek. Jeśli nie to pytaj.
