### ISSUE TITLE
edycja pisma przychodzącego (2 pliki)

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#103]
mam pismo przychodzące z jednym plikiem, zapomniałam o załaczniku do niego, czyli edytuję, żeby wrzucić więcej plików niż jeden , a tu jest "Nie masz uprawnień do zmiany plików tego pisma. Może to zrobić tylko: undefined" ??

**Comment by Tymczyszyn** [comment]
"Nie masz uprawnień do zmiany plików tego pisma. Może to zrobić tylko: monika.tymczyszyn28@gmail.com"
![image](https://user-images.githubusercontent.com/44840101/68125194-42196c00-ff11-11e9-9720-f07fdee5d1fe.png)
i też nie mogę tego zrobić

**Comment by oramm** [comment]
poprawione - powinni ju działać od paru dni
