### ISSUE TITLE
pisma przychodzące z 2 plikami

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#104]
Element „fileGdId” nie został zdefiniowany.

**Comment by oramm** [comment]
ale napisz czy błąd wychodzi przy dodwaniu czy przy edycji?

Tak jak mówiłem zawsze trzeba sprawdzić DEU (Dodowanie, Edycja, Usuwanie)

**Comment by Tymczyszyn** [comment]
błąd jest przy dodawaniu, edycja działa przy opisach , przy zmianie plików 1 do 1 tak, przy większej liczbie nie; usuwanie działa

**Comment by oramm** [comment]
poprawione powinno działać
