### ISSUE TITLE
rejestr pism wychodz. - opis komórki 

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#111]
Rejestruj pismo wychodzące po staremu - proszę o zmianę nazwy komórki  "data wpływu" na "data wysłania/nadania"

**Comment by oramm** [comment]
zrobione

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/69029187-86f2d780-09d4-11ea-8ddd-4cf535b8ebbb.png)

jest data wpływu

**Comment by oramm** [comment]
jak zrbione toMonika zamknij
