### ISSUE TITLE
nowy typ spraw - polecenia inżyniera

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#113]
Oprócz spraw związanych ze zgłoszeniami przydałby się też typ Polecenia Inżyniera, tu poszłyby wtedy wszystkie sprawy z porządkiem na budowie, zabezpieczeniami, bhp, ogólnie prowadzeniem robót, organizacją ruchu, bo teraz nie wiem gdzie to wrzucać,
chyba że pod kamień administracja umową zewnętrzną oprócz sprawy umowa coś dorzucisz...

**Comment by oramm** [comment]
dodano typ sprawy bieżące w kamieniu nadzór i projketowanie

**Comment by oramm** [comment]
jeśli temat jest załątwiony to zamknij zgłoszenie.
