### ISSUE TITLE
widok sprawy i wydarzenia 

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#114]
![image](https://user-images.githubusercontent.com/44840101/68936253-6f300f00-079a-11ea-8fb1-a9e80ac0926c.png)

**Comment by Tymczyszyn** [comment]
Zarejestrowałam 2 pisma: 1 wychodzące (kilka plików), 1 przychodzące (1 plik). Otwieram sprawę i wydarzenia gdzie są te pisma i:
- pismo z jednym plikiem mogę otworzyć i przeczytać (jest ikonka),
- pisma z załącznikami nie zobaczę (nie ma ikonki) 
![image](https://user-images.githubusercontent.com/44840101/68938489-c59f4c80-079e-11ea-930a-e29af3eb4574.png)

**Comment by Tymczyszyn** [comment]
Jeszcze jedno: przy piśmie wychodzącym w widoku jest "Od: Zakład Wodociągów i Kanalizacji Sp. z o.o. w Skawinie", zamiast DO

**Comment by Tymczyszyn** [comment]
"Ostania zmiana danych pisma: 15‑11‑2019 11:50 przez Marek Gazda"

**Comment by oramm** [comment]
naprawione.
