### ISSUE TITLE
Przerzucenie danych z projektu Dobromierza

### ISSUE THREAD

**Issue by trojnart** [oramm/ENVI.ProjectSite#115]
Zła nazwa projektu. DOB.GWS.01.PROW powinien się nazywać DOB.GWS.03.RPO.

**Comment by trojnart** [comment]
Prosiłeś o to zgłoszenie wiec niniejszym z marszu dodałem.

**Comment by oramm** [comment]
'DOB.GWS.01.PROW' to była dobra nazwa, trzeba poprzenosić tylko kontrakty do DIB.GWS.RPO.02

**Comment by oramm** [comment]
OK jest poprzenoszone. Treraz treba dane wprowadzić i po prostu tego używać

**Comment by trojnart** [comment]
Dobrze ale dlaczego do DOB.GWS.RPO.02 skoro to jest nasz trzeci projekt? Nie rozumiem tej filozofii kompletnie.

**Comment by oramm** [comment]
@trojnart Jeżeli temat jest załątwiony to zamknij zgłoszenie.
