### ISSUE TITLE
Rejestrcpism widok (od /do)

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#116]
W pismach wychodzących Envi do … w widoku jest "od" i nazwa adresata

**Comment by oramm** [comment]
o jaki widok chodzi? napisz które okno i miejsce systemy?

**Comment by Tymczyszyn** [comment]
w liście - rejestr pism

**Comment by oramm** [comment]
Monika @Tymczyszyn to już chyba działa poprawnie.
Zamknij jeśli tak.
