### ISSUE TITLE
pismo nie przypisane do sprawy

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#118]
tzn. jest pod sprawą, ale nie właściwą, przy edycji usunęłam złą, a nowej nie mogę dać.
SKW pismo z 18.12.2018 r.  jest pod sprawą Personel IK (wydarzenia), a ma być pod inicjacją, na GD przesunęłam ręcznie, więc na to nie patrz, w rejestrze jest bez sprawy
![image](https://user-images.githubusercontent.com/44840101/69051896-ec12f100-0a05-11ea-90e6-5e10614110e2.png)

**Comment by Tymczyszyn** [comment]
już się samo naprawiło :) zamykam zgłoszenia

**Comment by oramm** [comment]
> już się samo naprawiło :) zamykam zgłoszenia

?? czyli jak jest?
