### ISSUE TITLE
wnioski materiałowe - podfolder

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#119]
W Skawinie mam podfolder (S01) 
![image](https://user-images.githubusercontent.com/44840101/69129146-1e782900-0aae-11ea-9767-36467a204e18.png)

**Comment by Tymczyszyn** [comment]
a w Kobierzycach wnioski wskakują pod razu pod "07.01 Wnioski materiałowe" jest S00, zrób proszę tak samo w Skawinie
![image](https://user-images.githubusercontent.com/44840101/69129318-67c87880-0aae-11ea-91c4-cb552921a85e.png)

**Comment by oramm** [comment]
ostatnio zdecyfowaliśmy, że wniosko są sprawą unikalną. DLatego wskakują od razu pod folder typu 07.01 bezpośrednio.
ALe za to każdy wniosek dostaje swój własny folder.
Dlaczego chcesz wrócić do tworzenia folderów sprawy dla każdego wniosku?

**Comment by oramm** [comment]
ja chcę ukryć w ogóle widok typu sprawy 07.01 w widoku lusty spraw. Wnoiski materiałowe miałyby tylko jedno swoje miejsce. 
Tzn zakładkę "Materiały"

**Comment by Tymczyszyn** [comment]
nie, chcę żeby Skawina nie miała podfolderu S01 :) , tak jak piszesz, wnioski mają być sprawą unikalną - jedno miejsce

**Comment by Tymczyszyn** [comment]
nie napisałam "tak samo jak w Skawinie" tylko "rób proszę tak samo w Skawinie" czyli tak jak w Kobierzycach bez podfolderu  : )

**Comment by oramm** [comment]
ok, jasne (...ufff, już się bałem:))

**Comment by oramm** [comment]
Monika sprawdziłem.
W części kontraktów faktycznie jest S01, ale w części już niema.
Żeby pozbyć się S01 musisz:
- usunąć sprawę wnioski materiałowe.
- dodać ją na nowo. 
pamiętaj że jeśli masz już wniosku wcześniej dodane to musisz je dodać na nowo (moim zdaniemi wtedy już lepiej zostawić jak jest z S01).

**Comment by Tymczyszyn** [comment]
a jak utworzę nową sprawę wnioski materiałowe S0, to nie mogę przenieść folderów z wnioskami i wtedy usunąć sprawy wprowadzonej "po staremu" (z S01) ?  Za dużo ich już wprowadziłam … tylko czy przez rejestr się do nich dostanę ?

**Comment by oramm** [comment]
Nie.. musiałabyś usunąć sprawę utworzyć na nowo (bo nie mogą istenić dwie sprawy 7.1).
Każdy wniosek ma przypisaną sprawę, więc musiałabyć ponownie rejestrować wnioski, żeby system zrobił przypisanie

**Comment by oramm** [comment]
W przyszłości pomyślę nad tym, żeby w ogóle nie było sprawy 7.1. tylko goły folder - jak t jest z notatkami, dzie też ostatecznie znikął typ sprawy - rady budowy

**Comment by Tymczyszyn** [comment]
ok, zamykam
