### ISSUE TITLE
Rejestr pism - możliwość wklejania opisu

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#121]
Jak chcę wkleić nawet krótki opis, to wyskakują jakieś SPANY, i mimo, że nie przekraczam liczby znaków (albo  źle pokazuje, albo z opóźnieniem i wydaje się, że jest OK ), to pisma nie rejestruje ...

**Comment by oramm** [comment]
N arazie wklejaj tekst najpierw do notatnika a potem stamtąd do witryny.

Notatnik czyści tekst z formatowania.

**Comment by oramm** [comment]
zrobione. Teraz tekst będzie wklejany bez formatowania żadnego (bez pogrubienia, kolorów czcionek itp.

**Comment by oramm** [comment]
To dotyczy wszystkich miejsc w systemie
