### ISSUE TITLE
pismo trafiło do złego folderu

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#122]
zarejestrowane pismo  dot. sprawy - rozpoczęcie robót 
![image](https://user-images.githubusercontent.com/44840101/70169325-e1757e80-16ca-11ea-8c3f-1060615b7f41.png)

**Comment by Tymczyszyn** [comment]
jest we właściwym folderze i korespondencji, ale też w folderze 4.04 Podwykonawstwo, ale już w wydarzeniach tej sprawy nie 
![image](https://user-images.githubusercontent.com/44840101/70169741-b2134180-16cb-11ea-91d7-4401e58ba14d.png)
![image](https://user-images.githubusercontent.com/44840101/70169788-c9eac580-16cb-11ea-907b-48e48d2f4a0d.png)

**Comment by Tymczyszyn** [comment]
usuwam je z Podwykonawstwo, to mogło wynikać z tego, że jak nie mogłam podpiąć pisma pod Rozpoczęcie robót, to dałam na chwilę pod Podwykonawstwo, ale jak później zmieniłam na właściwą sprawę, to w folderze starej zostaje ?

**Comment by oramm** [comment]
nie. Powinno zniknąć, też na gd.
Przetestuj ten przypadek na innych pismach (przychodzących i wychodzących i daj znać czy błąd się powtarza.
Czasami zmiany na GD mogą być propagowane z opóźnieniem (obciążenie Google).

**Comment by oramm** [comment]
czy problem nadal występuje? Jeśli nie to zamknij to zgłoszenie.
