### ISSUE TITLE
Komunikat przy przejściu do kamieni milowych

### ISSUE THREAD

**Issue by UrszulaJuzwiak** [oramm/ENVI.ProjectSite#123]
![unknowncolumn](https://user-images.githubusercontent.com/45199703/70884913-98c99980-1fd7-11ea-866e-77cdb4cccfd8.png)

**Comment by oramm** [comment]
poprawione

**Comment by oramm** [comment]
zamknij jeśli potwierdzasz

**Comment by UrszulaJuzwiak** [comment]
działa
