### ISSUE TITLE
Kontrakt SCI zielń - usł. i nadzór - brakuje spraw bieżących

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#124]
W projekcie SCI.zieleń na kontrakcie nr 2 „Dokończenie dokumentacji projektowej dla zad. pn.: Rewitalizacja Ścinawy poprzez rozwój terenów zieleni miejskiej wraz z pełnieniem nadzoru aut.” w kamieniu "Usługa i nadzór" brakuje sprawy pn. "sprawy bieżące" , Dodaj proszę.

**Comment by oramm** [comment]
taka sprawa jest dodana.
