### ISSUE TITLE
Umowa ENVI - przypisywanie koordynatorów i administratorów

### ISSUE THREAD

**Issue by UrszulaJuzwiak** [oramm/ENVI.ProjectSite#126]
Przy rejestrowaniu nowej umowy, w polach Koordynator i Administrator nie można wprowadzić żadnego użytkownika - nie wyświetla się lista możliwych użytkowników. 
Błąd stwierdzony na projekcie AQM

**Comment by oramm** [comment]
ok już widzę, lista teraz jest inicjowana na podstawie listy kontaktowej w projekcie.
Jeśli nikogo tam nie dodano to nie można też przypisać koordynatora.
Widzę, ze jest dodana Urszula i tylko Ją można ustawić jako Koordynatora/admina
To jest spójne i logiczne.

**Comment by oramm** [comment]
@UrszulaJuzwiak jeśli potwierdzasz zamknij zgłoszenie

**Comment by UrszulaJuzwiak** [comment]
działa
