### ISSUE TITLE
Kontakty

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#13]
Przypisując osobę do roli w kontrakcie z naszej bazy, np. przy Al. Raginisie jest dodatkowo Powiatowy Zarząd Dróg

**Comment by oramm** [comment]
Zrobione.
1. W  systemie można oznaczyć osoby jako **'współpracownik ENVI'**. Na razie mogę to zrobić tylko ja.
2. Od teraz w liście kontaktowej dla każdego z projektów nazwa firmy dla osób oznaczonych w systemie jako **Współpracownik ENVI** jest maskowana. System wyświetla tekst "ENVI". Ale w ksiżce telefonicznej (erp.envi.com.pl) widać nazwę firmy tej osoby pod jaką prowadzi działalność.
