### ISSUE TITLE
Witryna - zarządzaj rolami

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#15]

**Comment by Tymczyszyn** [comment]
Dodaję rolę, zapisuję i nic się nie dzieje

**Comment by oramm** [comment]
Sprawdziłem u mnie działa.
Sprawdź jeszcze raz i potwierdź czy jest ok.

**Comment by Tymczyszyn** [comment]
jest ok

**Comment by oramm** [comment]
Zamykam temat w takim Bądź razie. 👍.
