### ISSUE TITLE
lista kontaktowa

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#19]
określiłam role, chcąc je przypisać, nie rozwija się lista ról

**Comment by oramm** [comment]
OK. Udało się naprawić. Można robić listy kontaktowe.
Usunąłem też przy okazji błąd przy usuwaniu osoby z listy. Już nie trzeba odświeżać strony (jeśli ktoś w ogóle to zauważył :))
