### ISSUE TITLE
Moje envi  - kontakty

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#20]
Wpisałam podmiot, wpisałam kontakt, zaciągnęłam  dane pomiotu w kontakcie, zapisałam, jest OK.
Drugi raz robię to samo (inny podmiot i kontakt - Biuro obsługi inwestycji Rafał Andrzejczak) i przy wierszu Firma, mimo wpisanego podmiotu i wyboru go z listy, wyskakuje komunikat "Podaj wartość w wymaganym formacie" i nie można kontaktu zapisać .

**Comment by oramm** [comment]
Ok. przeanalizuję to. Na razie gdy taki błąd wyskakuje trzeba odświeżyć stronę.

**Comment by Tymczyszyn** [comment]
Dzisiaj była próba nr 4 i nie mogę wprowadzić Andrzejczaka, odświerzałam

**Comment by Tymczyszyn** [comment]
Tak samo w podmiotach jest ADESI, wpisałam w kontaktach Paweł Winturski, ale nie mogę podpiąć mu jego firmy - ADESI, w tej chwili jest ATA Technik, bo wyskakuje komunikat o złym formacie.

**Comment by oramm** [comment]
na końcu nazwy podmiotu dodałaś spację. To jest przyczyną problemu. usuń spację na końcu i na początku nazwy podmiotu (jeśli występuje).

**Comment by oramm** [comment]
W międzyczasie poprawiłem system, tak że sam obcina spacje z początku i końca pól formularz podmiotu.

**Comment by oramm** [comment]
łooo... ADESI to w ogóle jest tak wprowadzone: 'ADESI Sp. z o.o.       '

Siedem spacji na końcu :)

**Comment by oramm** [comment]
Jak pisałem wcześniej już powinno działać. POtwierdź to Monika

**Comment by Tymczyszyn** [comment]
działa, te spacje to przez kopiowanie ? bo nie zawsze wpisuję z palca

**Comment by oramm** [comment]
Tak, 👍 one się przyklejają przy kopiowaniu.

Zdarza się też czasem jak ktoś zaśnie nad klawiaturą:). Spacja jest największym klawiszem... i wiadomo... :)
