### ISSUE TITLE
Witryna - kontakty

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#21]
Tworzę listę kontaktową KOB przypisując role. Wpisałam Roberta Pazdana (jest w kontaktach), ale wyskakuje komunikat "Podaj wartość w wymaganym formacie" i nie można zapisać.

**Comment by oramm** [comment]
Widzę, że już dodałąś Roberta.
JEśli zgłoszenie jest nieaktualno to je zamknij proszę.
