### ISSUE TITLE
Witryna - kontakty lp.

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#24]
Czy można dodać liczbę porządkową do ról i listy kontaktowej ? bo wtedy wiadomo od razu czy wszystkich się wpisało czy nie.

**Comment by oramm** [comment]
można.

**Comment by oramm** [comment]
Wprowadzę liczbę zapisanych pozycji na liście zamiast lp. to będzie łątwieszje. a Efekt też będzie zgodny z zamierzonym

**Comment by Tymczyszyn** [comment]
to wprowadź proszę

**Comment by Tymczyszyn** [comment]
nie zamykam, bo nie ma lp. ani sumy wprowadzonych pozycji

**Comment by oramm** [comment]
już wprowadziłem sume osób, ale po dodaniu wymaga odświeżenia zakładki - trzeba jeszcze raz kliknąć na link osoby w projekcie lub przy kontrakcie.
