### ISSUE TITLE
Edycja kontraktu

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#25]
Wpisałam nazwę kontraktu:  Zadanie 4.1 - Budowa sieci kanalizacyjnej w gm. Skawina Jaśkowice-Zelczyna - część I; Zadanie 5.1 - Budowa sieci kanalizacyjnej w gm. Skawina Grabie-Krzęcin - część I.
Komunikat: "Niewłaściwy format danych" i nie wiadomo o co chodzi.

Okazało się , że się nie mieści, musiałam skrócić do "4.1- Budowa sieci kanalizacyjnej w gm. Skawina Jaśkowice-Zelczyna - cz. I; 5.1 - Budowa sieci kanalizacyjnej w gm. Skawina Grabie-Krzęcin - cz. I" więc 150 znaków to za mało, bo np. w tym przypadku kontrakt obejmuje 2 zadania i nie mogę wpisać pełnej nazwy z umowy.

**Comment by oramm** [comment]
Przyczyna już odnaleziona.
Psuje się po edycji pola kontraktu w okeni edycji kamienia milowego. Na dniach to naprawię.
Na razie po każdym przypisaniu kontraktu do kamienia trzeba klikać na menu "kontrakty, żeby odświeżyć panel kontraktów.
Edycja innych pól nie psuje niczego.

**Comment by oramm** [comment]
Naprawiono.
