### ISSUE TITLE
Kamień milowy - kontrakt

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#26]
Miałam wpisany kontrakt nr...  więc dałam edycję żeby dopisać "- realizacja" (kamień milowy). Przy 2-3 krotnej próbie wyskoczył komunikat "Do wykonania tej czynności wymagana jest autoryzacja", za czwartym razem się udało.

**Comment by Tymczyszyn** [comment]
skorygowałam 3 kolejne nazwy kamieni- kontraktów i jest Ok

**Comment by oramm** [comment]
na razie zamykam jak się powtórzy to otwórz na nowo ten wątek - nie zakldaj wtedy nowego.
