### ISSUE TITLE
Witryna - Nazwa roli

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#28]
Jest za mało miejsca, nie mogę wpisać pełnej zgodnie z tym co mam od Zamawiającego, np. jedno ze stanowisk: "Specjalista ds. organizacyjnych, zamówień publicznych, promocji i monitorowania Projektu JRP", musiałam skrócić do: "Spec. ds. organizac., zam. publ., promocji" .

**Comment by oramm** [comment]
Zrobione, Monika sprawdź czy działa i zamknij Zgłoszenie

**Comment by Tymczyszyn** [comment]
Działa, zamykam
