### ISSUE TITLE
SKW - brak kamieni

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#33]
Kamienie są wprowadzone w witrynie pod. SKW.IK.1, ale jak chcę w scrumie dodać zadanie, to lista kamieni jest pusta.

**Comment by oramm** [comment]
Wszystko działa:
![obraz](https://user-images.githubusercontent.com/33371875/58753220-2c180300-84bc-11e9-924c-2efa827cab51.png)

Pamiętaj, że przed dodawanie zadania trzeba zaznaczyć dowolną komórkę w dowolnym wierszu projketu w Scrumie (poza nagłówkiem).

**Comment by oramm** [comment]
W SKW nie dadano żadnej sprawy. Pamiętaj, że przed dodaniem zadania trzeba dodać sprawę.

**Comment by Tymczyszyn** [comment]
Tak, zgł. było z 26 marca, od tego czasu wiele się zmieniło :)

**Comment by Tymczyszyn** [comment]
zamykam bo to jest nieaktualne
