### ISSUE TITLE
OLE - brak kamieni

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#34]
Kamienie są wprowadzone w witrynie pod OLE.IK.1, ale jak chcę w scrumie dodać sprawę i zadanie dot. zadania 10 "Roboty - nadzór | zad. 10 (Sądowa, Murka, Sienkiewicza)" , tego kamienia nie widać

**Comment by oramm** [comment]
yyy... bo takiego kamienia nie dodałaś w witrynie :).

Dodaj kamień i powinno działać nie ma tu żadnego błedu systemu.
Jak załątwisz sprawę, zamknij zgłoszenie.

**Comment by Tymczyszyn** [comment]
to coś się zamieszałam, faktycznie nie ma, tylko kontrakt

**Comment by Tymczyszyn** [comment]
dodaję kamień dla zad. 10 i wyskakuje komunikat "Exception: Duplicate entry '5--100' for key 'UNIQUE_Milestone' ?

**Comment by oramm** [comment]
> 
> 
> Kamienie są wprowadzone w witrynie pod OLE.IK.1, ale jak chcę w scrumie dodać sprawę i zadanie dot. zadania 10 "Roboty - nadzór | zad. 10 (Sądowa, Murka, Sienkiewicza)" , tego kamienia nie widać

Zadania 10 nie ma w ogóle. jest połączone zadanie 05, 08, 10. i **To zadanie widoczne jest w scrumie**:
![obraz](https://user-images.githubusercontent.com/33371875/58812399-19b7d980-8622-11e9-941f-8ed4d7f034fc.png)

**Comment by oramm** [comment]
Monika, zamknij to zgłoszenie, jeśli jest nieaktualne
