### ISSUE TITLE
KOB - brak kamieni

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#35]
W KOB brakuje listy kamieni dot. umowy IK

**Comment by Tymczyszyn** [comment]
… typów kamieni dla IK

**Comment by oramm** [comment]
to zostało naprawione. Potwierdź, jeśli zobaczysz że jest ok, to zamknij zgłoszenie.

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/58777611-5ad2ce00-85cf-11e9-973f-7d8a7ee1c2d8.png)

**Comment by Tymczyszyn** [comment]
są wprowadzone kamienie (przez Ciebie ?) m.in. Roboty-nadzór, ale jak rozwijam listę przy umowie IK, to wyświetla się jw. - kamienia na nadzór tu nie ma

**Comment by oramm** [comment]
Nie widzisz bo najpierw trzeba wybrać jakiego kontraktu na roboty kamień dotyczy - pierwsze pole.

Sprawdź i zamknij zadanie

**Comment by Tymczyszyn** [comment]
Jest OK, zamykam
