### ISSUE TITLE
Uspójnienie nazewnictwa - typ/rodzaj sprawy

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#38]
czy typ sprawy to to samo co rodzaj sprawy ? jeśli tak to proszę o ujednolicenie nazewnictwa

**Comment by oramm** [comment]
Tak to są synomiy. Uspójnię nazewnictwo

**Comment by oramm** [comment]
Monika sprawdź czy można zamknąć temat i jak tak to zamknij
