### ISSUE TITLE
lista zadań - widok błędny okna

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#40]
o co chodzi ? podświetlam zadanie (już się nie kręci) daję edytuj, a edycja otwiera się z innego zadania i można sobie namieszać ...

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/58696149-3f7d7e00-8397-11e9-9f43-f035ac655d0f.png)

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/58696184-58862f00-8397-11e9-99fd-e63b234de695.png)

**Comment by Tymczyszyn** [comment]
podświetlone zadanie "nowe..." a edycja jest z zadania "coś tam"

**Comment by oramm** [comment]
nie mogę powtórzyć tego błędu. Może to był chwilowy probelm z netem. @Tymczyszyn  Daj znać czy mogę zamknąć to zgłoszenie.

**Comment by Tymczyszyn** [comment]
zamykamy, jak się powtórzy to dam znac
