### ISSUE TITLE
sprawa - typ, nazwa blokowana

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#42]
Jeśli sprawa nie może mieć nazwy, to pole nazwy powinno być zablokowane,

**Comment by oramm** [comment]
racja. zadanie idzie do kolejki

**Comment by oramm** [comment]
zrobione, sprawdź czy działa

**Comment by Tymczyszyn** [comment]
czyli typ sprawy, która nie potrzebuje nazwy nie ma wiersza z nazwą i super, zamykam
