### ISSUE TITLE
Nazwa sparwy blokowanie 2

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#44]
![image](https://user-images.githubusercontent.com/44840101/58800430-1879b300-8608-11e9-948b-d9ac1705c993.png)

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/58800477-3fd08000-8608-11e9-9bac-55ad65ece83c.png)

**Comment by Tymczyszyn** [comment]
wymusza podanie nazwy, a jak wpiszę to ...

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/58800526-65f62000-8608-11e9-8fa9-b9f38c888548.png)

**Comment by Tymczyszyn** [comment]
więc nazwa musi być blokowana jeśli sprawa nie może mieć nazwy

**Comment by Tymczyszyn** [comment]
z poziomu witryny dodałam sprawę (typ) bez nazwy i zadanie i jest ok, pojawiło się w scrumie, ale z poziomu scruma sprawy nie udało się dodać ...

**Comment by oramm** [comment]
@Tymczyszyn czy problem nadal występuje? powinien już być do zamknięcia

**Comment by Tymczyszyn** [comment]
do sprawdzenia

**Comment by oramm** [comment]
Przerobiłem okno dodawania spraw w scrumie. Teraz działa intuicyjnie.
