### ISSUE TITLE
Dodawanie sprawy w scrub - błędne okno

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#45]
![image](https://user-images.githubusercontent.com/44840101/58801079-d94c6180-8609-11e9-90ea-c7448744ac13.png)

**Comment by Tymczyszyn** [comment]
jestem w OLE.IK.01, okno wyskoczyło GRO.IK.01, jak komórkę mam podświetloną 2 wiersze wyżej to już jest OK, czyli że co ? nie można za bardzo oddalać się od wiersza z numerem projektu ??? :)
od 17 wiersza tak się dzieje :)

**Comment by oramm** [comment]
Faktycznie, błąd naprawiony. Fotyczył tylko paru strych wierszy w oleśnie. TO nie błąd systemu. Powodem było ręczne tworzenie wierdzy podczas lplanowania przeze mnie. W pośpiechu skopiowałem kod projketu z grodkowa.
