### ISSUE TITLE
kamienie-kontrakt na roboty

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#48]
Jak chcę dodać kamień przy kontrakcie na roboty to wyskakuje komunikat
"TypeError: Nie można odczytać właściwości „id” z elementu undefined"

**Comment by Tymczyszyn** [comment]
Kobierzyce

**Comment by oramm** [comment]
Naprawione. Błąd wynikał z przeróbki dodawania kamieni. Tzn teraz kamienie - poza tymi ogólnymi - dodajemy do kontraktów na roboty.
