### ISSUE TITLE
Witryna - zadanie dla Lidki

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#49]
![image](https://user-images.githubusercontent.com/44840101/60252224-2dc1c480-98ca-11e9-8eac-fdfe517ba300.png)

**Comment by oramm** [comment]
Naprawione.
Teraz do Scruma dodają się tylko zadania :
1. przypisane do pracowników z biura
2. posiadające każdy status inny niż "Backlog"
