### ISSUE TITLE
Witryna - kamienie milowe

### ISSUE THREAD

**Issue by agnieszkadrozdek89** [oramm/ENVI.ProjectSite#50]
Zarejestrowane kamienie milowe nie sa widoczne w SCRUMie

![error 403](https://user-images.githubusercontent.com/48511109/60880115-42e01100-a243-11e9-8c16-d057a4b74e0f.png)
![error 404](https://user-images.githubusercontent.com/48511109/60880116-42e01100-a243-11e9-8521-711e6f696fe0.png)

**Comment by oramm** [comment]
naprawione
