### ISSUE TITLE
zadania - lista osób 

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#53]
W witrynie miała być możliwość przypisywania zadań dla wszystkich członków personelu IK, nie tylko nas biurowych, a na liście rozwijalnej jesteśmy tylko my. Powinni być wszyscy z listy kontaktowej danego projektu/kontraktu

**Comment by oramm** [comment]
po ostatniej rozmowie nt. roli scrumboarda zamykam ten wnoisek,
