### ISSUE TITLE
SKW kontrakt Ik - kamienie

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#54]
chcę skasować kamienie dot. nadzoru z umowy IK i jest komunikat "Nie udało się znaleźć żadnego elementu o danym identyfikatorze lub nie masz uprawnień pozwalających na dostęp do takiego elementu."

**Comment by oramm** [comment]
który projektk i kontrakt? skawina?

**Comment by Tymczyszyn** [comment]
jak w tytule, chodziło o Skawinę, ale już jest poprawiona, zamykam
