### ISSUE TITLE
Wnioski materiałowe

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#57]
Nie mogę nic wprowadzić, po chwili komunikat: Brak dostępu: DriveApp.

**Comment by Tymczyszyn** [comment]
i zagadka, bo teraz się udało

**Comment by Tymczyszyn** [comment]
nie tu coś nie działa, bo wyedytowałam daty, opis itd. i zniknęło.
Jako osoby odpowiedzialnej nie mogę wpisać ani inspektora ani Ali

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/61613721-5be4bb00-ac62-11e9-92d1-2bcecb4c2385.png)

**Comment by Tymczyszyn** [comment]
po zapisaniu wpis wygląda tak:

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/61613824-99494880-ac62-11e9-801e-d7a1908a3828.png)

**Comment by Tymczyszyn** [comment]
ja daję status "zakończone", to ma znika z listy ?

**Comment by Tymczyszyn** [comment]
znowu "Brak dostępu: DriveApp." i nawet przy statucie "w trakcie" wpis znika

**Comment by oramm** [comment]
wnioski narawione
