### ISSUE TITLE
Witryna - rejestr WM

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#6]
Wdrożenie i stosowanie elektronicznego rejestru wniosków materiałowych

**Comment by oramm** [comment]
gotowe, Monika sprawdź jak działa.

**Comment by Tymczyszyn** [comment]
Jest, tylko nie mogę zapisać przykładowego wpisu, coś blokuje w nazwie. Poza tym pytania:
1. Termin wykonania - co tu wpisywać ?
2. Osoba odpowiedzialna - czyli kto ? inspektor zatwierdzający dany wniosek ?
Na liście kontaktowej mam inspektorów, ale nie wyskakują w tym oknie, wpisywać z palca ?

**Comment by oramm** [comment]
>     1. Termin wykonania - co tu wpisywać ?

Termin jaki wyznaczasz drugiej stronie

**Comment by oramm** [comment]
>     2. Osoba odpowiedzialna - czyli kto ? inspektor zatwierdzający dany wniosek ?
>         Na liście kontaktowej mam inspektorów, ale nie wyskakują w tym oknie, wpisywać z palca ?

to już zrobione jest
