### ISSUE TITLE
Wymusić przypisanie kontraktu na roboty do naszej usługi

### ISSUE THREAD

**Issue by trojnart** [oramm/ENVI.ProjectSite#61]
Próba zapisania/dodania kontraktu skończyła się w taki sposób:
![Komunikat](https://user-images.githubusercontent.com/46750319/61928571-28af6e00-af79-11e9-84b5-2ce185cfd0a9.png)

**Comment by oramm** [comment]
to już powinno działć. Tylko pamiętaj żę kontrakt na roboty musi być przypisany do jedne z naszych usług.

**Comment by oramm** [comment]
W sumie to trzeba dodać zabezpieczenie przed możliwośćią nieprzypisania kontraktu na roboty do naszej usługi. OTwieram jednak ponwnie.

**Comment by oramm** [comment]
ok zrobione.
