### ISSUE TITLE
Błąd dostępu dla Arkadiusza Rojewskiego

### ISSUE THREAD

**Issue by UrszulaJuzwiak** [oramm/ENVI.ProjectSite#62]
Przy próbie logowania nie ładuje się strona oraz pojawiają się komunikaty błędu
Illegal operation on empty result set

adres użytkownika
rojarek0305@gmail.com

**Comment by oramm** [comment]
Potrzebuję więcej informacji

**Comment by UrszulaJuzwiak** [comment]
![image](https://user-images.githubusercontent.com/45199703/64970641-86d83d80-d8a6-11e9-9fa5-57d752f0eb4d.png)
https://photos.google.com/share/AF1QipMTqlI-IO-nLQ4CpE4J5KHkIXiu1aJEKXcnq7f0X0T8vpVTt7F4ntZg0OQX8Gcg2A?key=Z2x6ZUlQWG9paXB3V2Nfcjk3R2doSmJ5ejg0MFNR

**Comment by oramm** [comment]
Poprawiono przy Świadku J. :)
proszę potwierdzenie i zamknięciem jeśli działa @UrszulaJuzwiak
