### ISSUE TITLE
Dostęp dla Hodowanego (NOW)

### ISSUE THREAD

**Issue by UrszulaJuzwiak** [oramm/ENVI.ProjectSite#65]
błąd 
serverFunctionName: Exception: unknown column 'undefined' in 'where clause'

![hodowany_blad](https://user-images.githubusercontent.com/45199703/64951917-4618fe00-d87f-11e9-8e3b-8bbafba4bc9d.png)

użytkownik: piotrh6211@gmail.com

**Comment by oramm** [comment]
Duplikat #62
