### ISSUE TITLE
edycja rejestru wniosków materiałowych

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#66]
Wprowadzony wniosek materiałowy nie można wyedytować. 
KOB - wpisuję wniosek ze statusem "nowe",  zapisuję, otwieram, edytuję, zapisuję, idę do innej zakładki wracam i wprowadzonych zmian nie ma, tylko pierwotna wersja. Przy innych statusach jest to samo. Kto i kiedy może edytować ?
Dlaczego zmiana na status "zakończone" usuwa wniosek ? wtedy nie wiadomo co zostało złożone i jest już zatwierdzone.

**Comment by Tymczyszyn** [comment]
Poza tym wprowadzony wniosek wskakuje do listy spraw, jak wprowadzę 20 wniosków, to będę miała dodatkowo 20 spraw, nie zamknę ich, bo mi znikną z listy, to po co je wprowadzać, chyba, że tylko aktualne (bieżące). W Kobierzycach większość wniosków jest zatwierdzonych, nowych jeszcze nie ma, to teraz lista "Materiały" powinna być pusta ? Jako Zamawiający chciałabym wiedzieć jakie materiały zostały zatwierdzone, wtedy mogę kontrolować czy właściwy materiał wbudowują itd.

**Comment by Tymczyszyn** [comment]
Jak podpiąć pod wniosek załączniki ?  Całość poleci do właściwego folderu na GD ?

**Comment by oramm** [comment]
Po ustaleniach wprowadzono zmiany do rejestru wniosków.
Sprawa 'wnioski materiałowe' jest unikalna w kamieniu. Obejmuje ona wszystkie wnioski.

Dodanie wniosku w witrynie powoduje:
 - utworzenie folderu dla tego wniosku w folderze sprawy 7.1
 - dodanie zadania do scruma.

Pamiętaj że nie ma automatycznego powiązania wniosku materiałowego z zadaniami. tzn można tworzyć zadania ogólnie dla sprawy 'Wnioski materiałowe'.

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/65418163-21330680-ddfc-11e9-85da-b316fe4f6eff.png)

**Comment by Tymczyszyn** [comment]
1. nie mogę dodać wniosku,
2. z automatu wskakuje data złożenia dzisiejsza, jak wprowadzę archiwalne, to mi przyjmie z datą wcześniejszą ?
3. ad. osoba odpowiedzialna: w archiwalnych wpisach w Kob, to Piotr Pazdan się tym zajmował, później Ala, ale jej też nie mogę tu wybrać

**Comment by Tymczyszyn** [comment]
Rozwijalna lista osób odpowiedzialnych powinna pokrywać się z listą kontaktową kontraktu, bo teraz jest tylko envi

**Comment by oramm** [comment]
> 
> 
> Jak podpiąć pod wniosek załączniki ? Całość poleci do właściwego folderu na GD ?

Pojawia się ikona Drive. Po kliknięciu w nią otwiera się okno folderu na GD, do którego trzeba wrzucać pliki.

**Comment by oramm** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/44840101/65418163-21330680-ddfc-11e9-85da-b316fe4f6eff.png)

to zostało naprawione już można dodawać wnioski i inne rzeczy gdzie występował ten błąd

**Comment by oramm** [comment]
>
>     1. nie mogę dodać wniosku,
> 
Dlaczego nie możesz. Moim zdaniem możesz. Jeśli chodziło o błąd: DriveApp: brak dostępu to jw. - załatwione.

**Comment by oramm** [comment]
>     2\. z automatu wskakuje data złożenia dzisiejsza, jak wprowadzę archiwalne, to mi przyjmie z datą wcześniejszą ?

Tak przyjmuje datę wcześniejszą. To tylko jest podpowiedź.

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/65592541-0b097f80-df8f-11e9-8dd9-cfdc9e4a149a.png)

**Comment by oramm** [comment]
>     3. ad. osoba odpowiedzialna: w archiwalnych wpisach w Kob, to Piotr Pazdan się tym zajmował, później Ala, ale jej też nie mogę tu wybrać

Poprawiono, teraz lista osób jest identyczna jak lista kontaktowa w projekcie.

**Comment by oramm** [comment]
> Dlaczego zmiana na status "zakończone" usuwa wniosek ? wtedy nie wiadomo co zostało złożone i jest już zatwierdzone.

Naprawione.
