### ISSUE TITLE
brak dostępu przez przeglądarkę IE 

### ISSUE THREAD

**Issue by UrszulaJuzwiak** [oramm/ENVI.ProjectSite#67]
Przy próbie logowania do witryny przez IE  system zatrzymuje się na takim widoku

![przegIE](https://user-images.githubusercontent.com/45199703/65218769-764ae180-dab7-11e9-87cb-e7cc597ae09d.png)

**Comment by oramm** [comment]
Nie będziemy tego naprawia. NIe należy korzystać z IE.
