### ISSUE TITLE
pisma - znikające sprawy

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#69]
![image](https://user-images.githubusercontent.com/44840101/65421700-a9b5a500-de04-11e9-9376-3025c2e7dfa1.png)

**Comment by Tymczyszyn** [comment]
![image](https://user-images.githubusercontent.com/44840101/65421763-d669bc80-de04-11e9-8506-96f11b644e1b.png)

**Comment by Tymczyszyn** [comment]
Rejestruję pismo w KOB, na liście rozwijalnej spraw mam tylko Inicjację i Zakończenie. Przy drugiej edycji tego pisma, na tej liście są tylko sprawy ogólne i zamknięcie (nie ma inicjacji). Przy trzeciej edycji znowu inicjacja i zamknięcie (bez spraw ogólnych) i tak w kółko.

**Comment by Tymczyszyn** [comment]
problem ciągle występuje, jak pismo nie zostanie zapisane (niewiadomo z jakichnpowodów)  to przy kolejnej próbie trzeba ponownie wybrać sprawę, tylko że tej sprawy nie ma na liście ...

**Comment by oramm** [comment]
poprawione - powinno działać.

**Comment by oramm** [comment]
@Tymczyszyn  Monika sprawdź i jeśli działa to zamknij zgłoszenie
