### ISSUE TITLE
Witryna - problemy, zgłoszenia

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#7]
Rejestr spornych i trudnych kwestii

**Comment by oramm** [comment]
Już powinno działać @Tymczyszyn prośba  sprawdzenie. Weź przy okazji popraw jakoś login, bo samo nazwisko wskazuje. A po nazwisku to nie łądnie :)

**Comment by Tymczyszyn** [comment]
czyli to jest nasza zakładka "zgłoszena" ? to zamykam :)
