### ISSUE TITLE
Umowa IK łączona z PT

### ISSUE THREAD

**Issue by AgnieszkaBK** [oramm/ENVI.ProjectSite#71]
Na Wągrowcu i Mogilnie mam umowy łączone - i na IK i na PT. Żeby mieć odpowiedni wybór kamieni milowych powinnam rozdzielić umowę na dwie, osobno na IK i osobno na PT? 
Na Wągrowcu mam w umowie podział wynagrodzenia więc tu dałoby się to zrobić, w Mogilnie natomiast mam umowę na inżyniera kontraktu a w ramach kontraktu są zadania pomocy technicznej.

**Comment by oramm** [comment]
nie.
Muszę uzupełnić dostępną liste kamieni dla usługi IK. Rano to zrobię i dam znać.

**Comment by oramm** [comment]
@AgnieszkaBK czy nadal brakuje kamieni? jesli nie to zamknij zgłoszenie

**Comment by oramm** [comment]
@AgnieszkaBK ponawiam prośbę.

**Comment by oramm** [comment]
albo zamykam temat i już :)
