### ISSUE TITLE
KOB - procedury

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#8]
Procedura monitorowania ryzyk i procedura kontroli wykonania przeciwdziałań	
- Procedura monitorowania ryzyk.
- Procedura kontroli wykonania przeciwdziałań
- Identyfikacja i analiza jakościowa ryzyk	
- Analiza ilościowa ryzyk metodą Monte Carlo

**Comment by oramm** [comment]
Trzeba dodać zasadę, żę jeżeli sprawa jest ryzykiem, to dotyczą ją procedury zarządzania ryzykami.
Procedury te mają się wyświetlić w panelu zadań w witrynie

**Comment by oramm** [comment]
Zgodnie z Metodyka Rejestr Ryzyk ma być zgodny z pkt 5. Metodyki.
Oznacza to że ma umożliwiać realziację tego punktu. Sa, pnkt 5 mówi jak monitorować ryzyka z wykorzystaniem rejestru.
CHodzi o to, żeby był rejestr który może być używany zgodnie z pkt. 5 

Analiza ilościowa ryzyka zgodnie z pkt. 5 była wykonana na etapie oferowania. NIe jet ona częścią rejestru ryzyk. Aktuakizacji w rejestrze podlegają jedynie parametry ryzyk tj prawdopodobieństwo, skutki, właściciel, działąnia naprawcze.

Ala Musu wprowadzić ryzyka do rejestru i regularnie je przeglądać.

Ten moduł już działa. W zaadzie jeśli nie ma błędów w działaniu Zamknij Monika to zgłoszenie.
