### ISSUE TITLE
WAG.IK.01 GD

### ISSUE THREAD

**Issue by AgnieszkaBK** [oramm/ENVI.ProjectSite#89]
Kamień WAG.IK.01 "Administracja" nie powiązana jest na drive z folderem WAG.IK.01

**Comment by oramm** [comment]
Jakie operacje wykoawnałaś na tej sprawie. Czy ją usuwałaś i dodawałaś?

**Comment by AgnieszkaBK** [comment]
usunęłam cały stary WAG.
Zrobiłam go na nowo. Zobaczyłam że "Administracja" nie jest powiązana z folderem WAG.IK.01, więc go usunęłam  i wprowadziłam jeszcze raz - problem powtórzył się.

**Comment by oramm** [comment]
usunąłem jest porządek
