### ISSUE TITLE
dodać wybór z listy danych nadawców/odbiorców

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#91]
powinno być miejsce z danymi adresowymi IK, Zamawiającego i Wykonawców, dane to były by pomocne też przy rejestracji pism  (lista rozwijalna) itd. żeby za każdym razem nie wpisywać z palca

**Comment by oramm** [comment]
rozumiem ze te dane powinny być w notatkach, a nie w piśmie?

**Comment by Tymczyszyn** [comment]
przy rejestracji trzeba wpisać dane nadawcy/odbiorcy, to wtedy tez mogłaby być lista rozwijalna

**Comment by oramm** [comment]
ten wątek niech dotyczy notatek. Pisma poszły do osobnego zgłoszenia.

**Comment by oramm** [comment]
zrobione
