### ISSUE TITLE
Witryna/wnioski materiałowe/widok

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#96]
Po rozwinięciu danego wniosku jest opis i uwagi: undefined
Przy edycji nie ma pola na uwagi. Tak ma być ?

![image](https://user-images.githubusercontent.com/44840101/66912469-edba5500-f012-11e9-860d-ff4a5bad50d2.png)

**Comment by Tymczyszyn** [comment]
nie wiem dlaczego zrzut ekranu jest nie na temat ;/ ???

**Comment by oramm** [comment]
oczywiście to jest do poprawy

**Comment by oramm** [comment]
zrobione już wcześniej tylko zapomniałem zamnkąć zgłoszenie.
