### ISSUE TITLE
zamieszczanie pism podczas rejestru

### ISSUE THREAD

**Issue by kamila07071983** [oramm/ENVI.ProjectSite#97]
Zamieszczając więcej niż jeden załącznik w postaci pisma i dokumentów towarzyszących następuje zdublowanie pisma a nie zamieszczenie większej ilości załaczników

**Comment by oramm** [comment]
to już myślałem że jest naprawione. @kamila07071983 czy problem cały czas występuje po naszej rozmowie? czy może temat jet do zamknięcia?

**Comment by oramm** [comment]
wątek zamykam bo nie ma już tego problemu.
