### ISSUE TITLE
foldery, podfoldery różnice

### ISSUE THREAD

**Issue by Tymczyszyn** [oramm/ENVI.ProjectSite#98]
Kamila na KEP.IK.01  pod folderem "umowa" ma podfolder "administracja", u mnie na KOB i u Agi B. na MOG mamy folder "umowa" i równorzędny folder "administracja" (nie podfolder).  
Z kolei folder "okres gwarancji" o mnie jest podfolderem "Umowy", a u Agi równorzędny z umową i administracją. Dlaczego nie jest taka sama struktura ?

**Comment by oramm** [comment]
W naszej umowie powinien być folder '00 Umowa ENVI' jest to folder nie połączony z żadnym kamieniem.
Obok niego powinny być równolegle foldery kamieni milowych. Możesz w Kobierzycach ręcznie przenieść foldery. Nic się nie stanie - system ich nie pogubi, bo są podłączone po ID.  Byleby ich nie usuwać.

**Comment by Tymczyszyn** [comment]
Wszystkie zadania dot. umowy Envi i analogicznie wykonawców robót dajemy pod kamieniem administracja ?
